import type { Metadata } from "next";
import AuditWidget from "@/components/audit-widget";

export const metadata: Metadata = {
  title: "AI Brand Audit — Biz Reborn Marketing",
  description:
    "Get a free AI-powered brand audit. Discover your brand health score, uncover blind spots, and see how you stack up against local competitors.",
};

export default function AuditPage() {
  return (
    <div className="relative">
      <div className="absolute inset-0 bg-gradient-to-b from-brand-950/20 via-ink-950 to-ink-950" />
      <div className="relative mx-auto max-w-7xl px-4 pb-20 pt-16 sm:px-6 sm:pt-24 lg:px-8">
        <div className="mx-auto max-w-2xl text-center">
          <h1 className="font-sora text-3xl font-bold text-white sm:text-4xl">
            AI Brand Audit
          </h1>
          <p className="mt-3 text-sm leading-relaxed text-ink-400">
            Get a complete breakdown of your online presence, reputation score,
            and actionable fixes — all generated by our AI engine in under 60
            seconds.
          </p>
        </div>
      </div>
      <AuditWidget />
    </div>
  );
}
